import sample from 'lodash/sample';
import { Contributor } from 'src/redux/types';

const generatorContributors: Contributor[] = [
  {
    id: 65293,
    firstName: 'Bill',
    lastName: 'Klocko',
    registered: true,
    email: 'BillKlocko@gmail.com',
  },
  {
    id: 20531,
    firstName: 'Joesph',
    lastName: 'Block',
    registered: true,
    email: 'JoesphBlock@gmail.com',
  },
  {
    id: 34026,
    firstName: 'Johnson',
    lastName: 'Pollich',
    registered: true,
    email: 'JohnsonPollich@gmail.com',
  },
  {
    id: 45346,
    firstName: 'Golden',
    lastName: 'Hilpert',
    registered: true,
    email: 'GoldenHilpert@gmail.com',
  },
  {
    id: 82096,
    firstName: 'Willow',
    lastName: 'Cummings',
    registered: true,
    email: 'WillowCummings@gmail.com',
  },
  {
    id: 73220,
    firstName: 'Neoma',
    lastName: 'Bruen',
    registered: true,
    email: 'NeomaBruen@gmail.com',
  },
  {
    id: 70789,
    firstName: 'Lilyan',
    lastName: 'Boehm',
    registered: true,
    email: 'LilyanBoehm@gmail.com',
  },
  {
    id: 27072,
    firstName: 'Grace',
    lastName: 'Lemke',
    registered: true,
    email: 'GraceLemke@gmail.com',
  },
  {
    id: 95823,
    firstName: 'Abbie',
    lastName: 'Daniel',
    registered: true,
    email: 'AbbieDaniel@gmail.com',
  },
  {
    id: 16251,
    firstName: 'Liliane',
    lastName: 'Reichel',
    registered: true,
    email: 'LilianeReichel@gmail.com',
  },
  {
    id: 57110,
    firstName: 'Beulah',
    lastName: 'Denesik',
    registered: true,
    email: 'BeulahDenesik@gmail.com',
  },
  {
    id: 44829,
    firstName: 'Matt',
    lastName: "O'Connell",
    registered: true,
    email: "MattO'Connell@gmail.com",
  },
  {
    id: 87618,
    firstName: 'Oma',
    lastName: 'Moore',
    registered: true,
    email: 'OmaMoore@gmail.com',
  },
  {
    id: 67763,
    firstName: 'Timmy',
    lastName: 'Fadel',
    registered: true,
    email: 'TimmyFadel@gmail.com',
  },
  {
    id: 51593,
    firstName: 'Brandon',
    lastName: 'Keeling-Little',
    registered: true,
    email: 'BrandonKeeling-Little@gmail.com',
  },
  {
    id: 24546,
    firstName: 'Ludie',
    lastName: 'Rempel',
    registered: true,
    email: 'LudieRempel@gmail.com',
  },
  {
    id: 58157,
    firstName: 'Keanu',
    lastName: 'Rohan',
    registered: true,
    email: 'KeanuRohan@gmail.com',
  },
  {
    id: 43633,
    firstName: 'Kole',
    lastName: 'Wuckert',
    registered: true,
    email: 'KoleWuckert@gmail.com',
  },
  {
    id: 22487,
    firstName: 'Hoyt',
    lastName: 'Cummings',
    registered: true,
    email: 'HoytCummings@gmail.com',
  },
  {
    id: 24994,
    firstName: 'Jennyfer',
    lastName: 'Spencer',
    registered: true,
    email: 'JennyferSpencer@gmail.com',
  },
  {
    id: 13218,
    firstName: 'Scottie',
    lastName: "O'Keefe",
    registered: true,
    email: "ScottieO'Keefe@gmail.com",
  },
  {
    id: 10159,
    firstName: 'Jasmin',
    lastName: 'Wiegand',
    registered: true,
    email: 'JasminWiegand@gmail.com',
  },
  {
    id: 86457,
    firstName: 'Sophie',
    lastName: 'Russel',
    registered: true,
    email: 'SophieRussel@gmail.com',
  },
  {
    id: 12066,
    firstName: 'Verdie',
    lastName: 'Reynolds',
    registered: true,
    email: 'VerdieReynolds@gmail.com',
  },
];

export const generateContributor = (): Contributor => {
  return (
    sample(generatorContributors) ?? {
      id: 29237,
      firstName: 'Trycia',
      lastName: 'Parisian',
      registered: true,
      email: 'TryciaParisian@gmail.com',
    }
  );
};

export const demoContributors: Contributor[] = [
  {
    id: 76779,
    firstName: 'Emely',
    lastName: 'Marks',
    registered: true,
    email: 'EmelyMarks@gmail.com',
  },
  {
    id: 15279,
    firstName: 'Bennett',
    lastName: 'Marquardt',
    registered: true,
    email: 'BennettMarquardt@gmail.com',
  },
  {
    id: 20301,
    firstName: 'Trenton',
    lastName: 'Oberbrunner',
    registered: true,
    email: 'TrentonOberbrunner@gmail.com',
  },
  {
    id: 27038,
    firstName: 'Adrienne',
    lastName: 'McDermott-Ledner',
    registered: true,
    email: 'AdrienneMcDermott-Ledner@gmail.com',
  },
  {
    id: 48105,
    firstName: 'Maximilian',
    lastName: 'Graham',
    registered: true,
    email: 'MaximilianGraham@gmail.com',
  },
  {
    id: 46219,
    firstName: 'Eliza',
    lastName: 'Welch',
    registered: true,
    email: 'ElizaWelch@gmail.com',
  },
  {
    id: 99922,
    firstName: 'Felicita',
    lastName: 'Franey',
    registered: true,
    email: 'FelicitaFraney@gmail.com',
  },
  {
    id: 24116,
    firstName: 'Emelia',
    lastName: "O'Kon",
    registered: true,
    email: "EmeliaO'Kon@gmail.com",
  },
  {
    id: 28436,
    firstName: 'Rory',
    lastName: 'Denesik',
    registered: true,
    email: 'RoryDenesik@gmail.com',
  },
  {
    id: 58276,
    firstName: 'Breana',
    lastName: 'Donnelly',
    registered: true,
    email: 'BreanaDonnelly@gmail.com',
  },
  {
    id: 86125,
    firstName: 'Dejuan',
    lastName: 'Quigley',
    registered: true,
    email: 'DejuanQuigley@gmail.com',
  },
  {
    id: 46086,
    firstName: 'Peyton',
    lastName: 'Shields',
    registered: true,
    email: 'PeytonShields@gmail.com',
  },
  {
    id: 27430,
    firstName: 'Cesar',
    lastName: 'Strosin',
    registered: true,
    email: 'CesarStrosin@gmail.com',
  },
  {
    id: 38192,
    firstName: 'Daisy',
    lastName: 'McLaughlin',
    registered: true,
    email: 'DaisyMcLaughlin@gmail.com',
  },
  {
    id: 78832,
    firstName: 'Myra',
    lastName: 'McClure',
    registered: true,
    email: 'MyraMcClure@gmail.com',
  },
  {
    id: 96887,
    firstName: 'Christine',
    lastName: 'Kling',
    registered: true,
    email: 'ChristineKling@gmail.com',
  },
  {
    id: 40343,
    firstName: 'Cecelia',
    lastName: 'Kuvalis',
    registered: true,
    email: 'CeceliaKuvalis@gmail.com',
  },
  {
    id: 24249,
    firstName: 'Alyson',
    lastName: 'Treutel',
    registered: true,
    email: 'AlysonTreutel@gmail.com',
  },
  {
    id: 83635,
    firstName: 'Luis',
    lastName: 'Christiansen',
    registered: true,
    email: 'LuisChristiansen@gmail.com',
  },
  {
    id: 12704,
    firstName: 'Kristofer',
    lastName: 'Lebsack',
    registered: true,
    email: 'KristoferLebsack@gmail.com',
  },
  {
    id: 79511,
    firstName: 'Layne',
    lastName: 'Roob',
    registered: true,
    email: 'LayneRoob@gmail.com',
  },
  {
    id: 89671,
    firstName: 'Jaden',
    lastName: 'Kreiger',
    registered: true,
    email: 'JadenKreiger@gmail.com',
  },
  {
    id: 20003,
    firstName: 'Mekhi',
    lastName: 'Erdman',
    registered: true,
    email: 'MekhiErdman@gmail.com',
  },
  {
    id: 46858,
    firstName: 'Brenna',
    lastName: 'Reichel',
    registered: true,
    email: 'BrennaReichel@gmail.com',
  },
];
